
version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      db:
        image: mongo:latest
        hostname: test_mongodb
        environment:
          - MONGO_INITDB_DATABASE=usermanagementDb
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
          - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro