
version: '3'
services:
  app:
    build: .
    command: python -u app.py
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    container_name: mongo1
    environment:
      - MONGO_INITDB_DATABASE=userManagementDb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017